In [1]:
import pandas as pd

# Tạo DataFrame từ dictionary
data = {
    "Tên": ["An", "Bình", "Chi"],
    "Toán": [8, 7, 9],
    "Văn": [6, 8, 7],
    "Anh": [9, 7, 8]
}

df = pd.DataFrame(data)
print(df)

    Tên  Toán  Văn  Anh
0    An     8    6    9
1  Bình     7    8    7
2   Chi     9    7    8

In [8]:
print(df.dtypes)
print(df.shape)
df.info()

Tên     object
Toán     int64
Văn      int64
Anh      int64
dtype: object
(3, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Tên     3 non-null      object
 1   Toán    3 non-null      int64
 2   Văn     3 non-null      int64
 3   Anh     3 non-null      int64
dtypes: int64(3), object(1)
memory usage: 228.0+ bytes

In [9]:
print(df.describe())

       Toán  Văn  Anh
count   3.0  3.0  3.0
mean    8.0  7.0  8.0
std     1.0  1.0  1.0
min     7.0  6.0  7.0
25%     7.5  6.5  7.5
50%     8.0  7.0  8.0
75%     8.5  7.5  8.5
max     9.0  8.0  9.0

In [12]:
import pandas as pd

data = {
    "Tên": ["An", "Bình", "Chi"],
    "Toán": [8, 6, 9],
    "Văn": [7, 8, 9],
    "Anh": [9, 5, 8]
}

df = pd.DataFrame(data)

# Lưu ra file CSV
df.to_csv("diem.csv", index=False, encoding="utf-8")
print("Đã lưu ra file diem.csv")

df.to_excel("diem.xlsx", index=False, engine="openpyxl")
print("Đã lưu ra file diem.xlsx")

Đã lưu ra file diem.csv
Đã lưu ra file diem.xlsx

In [15]:
# Khởi tạo DataFrame bằng Dictionary
import pandas as pd
animals = pd.DataFrame({
    "dong_vat": ["Sao la", "Khỉ đuôi ngắn", "Voi châu Á"],
    "tuoi_tho": [25, 25, 70],
    "loai": ["có vú", "linh trưởng", "có vú"],
    "thuc_an": ["thực vật", "thực vật", "thực vật"],
    "moi_truong_song": ["Rừng", "Rừng", "Rừng"],
    "tap_tinh": ["Bầy đàn", "Bầy đàn", "Bầy đàn"]
})

animals

        dong_vat  tuoi_tho         loai   thuc_an moi_truong_song tap_tinh
0         Sao la        25        có vú  thực vật            Rừng  Bầy đàn
1  Khỉ đuôi ngắn        25  linh trưởng  thực vật            Rừng  Bầy đàn
2     Voi châu Á        70        có vú  thực vật            Rừng  Bầy đàn

In [16]:
# Hiển thị thông tin về bảng (số cột, số hàng, kiểu dữ liệu)
animals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   dong_vat         3 non-null      object
 1   tuoi_tho         3 non-null      int64
 2   loai             3 non-null      object
 3   thuc_an          3 non-null      object
 4   moi_truong_song  3 non-null      object
 5   tap_tinh         3 non-null      object
dtypes: int64(1), object(5)
memory usage: 276.0+ bytes

In [18]:
animals.head(2) # Xem n dòng đầu tiên
animals.tail(2) # Xem n dòng cuối cùng

        dong_vat  tuoi_tho         loai   thuc_an moi_truong_song tap_tinh
1  Khỉ đuôi ngắn        25  linh trưởng  thực vật            Rừng  Bầy đàn
2     Voi châu Á        70        có vú  thực vật            Rừng  Bầy đàn

In [22]:
# Dùng index slicing để lấy ra n hàng
animals[:2]

        dong_vat  tuoi_tho         loai   thuc_an moi_truong_song tap_tinh
0         Sao la        25        có vú  thực vật            Rừng  Bầy đàn
1  Khỉ đuôi ngắn        25  linh trưởng  thực vật            Rừng  Bầy đàn

In [ ]:
# Lấy ra 1 Series (1 cột)
animals["dong_vat"]

0           Sao la
1    Khỉ đuôi ngắn
2       Voi châu Á
Name: dong_vat, dtype: object

In [ ]:
# Lấy ra nhiều cột
animals[["dong_vat", "loai"]]

        dong_vat         loai
0         Sao la        có vú
1  Khỉ đuôi ngắn  linh trưởng
2     Voi châu Á        có vú

In [ ]:
# Lọc có điều kiện
age_data = animals[["dong_vat", "tuoi_tho"]]
age_data[animals["tuoi_tho"] <= 30]

        dong_vat  tuoi_tho
0         Sao la        25
1  Khỉ đuôi ngắn        25

In [ ]:
# Thay đổi index
animals.set_index("dong_vat", inplace=True)
animals

               tuoi_tho         loai   thuc_an moi_truong_song tap_tinh
dong_vat
Sao la               25        có vú  thực vật            Rừng  Bầy đàn
Khỉ đuôi ngắn        25  linh trưởng  thực vật            Rừng  Bầy đàn
Voi châu Á           70        có vú  thực vật            Rừng  Bầy đàn

In [ ]:
# Đặt index lại thành số
animals.reset_index()

        dong_vat  tuoi_tho         loai   thuc_an moi_truong_song tap_tinh
0         Sao la        25        có vú  thực vật            Rừng  Bầy đàn
1  Khỉ đuôi ngắn        25  linh trưởng  thực vật            Rừng  Bầy đàn
2     Voi châu Á        70        có vú  thực vật            Rừng  Bầy đàn

In [30]:
# Lọc dựa trên index
animals.iloc[:2, 0:3]

               tuoi_tho         loai   thuc_an
dong_vat
Sao la               25        có vú  thực vật
Khỉ đuôi ngắn        25  linh trưởng  thực vật

In [ ]:
# Lọc dựa trên dữ liệu
animals.loc[["Sao la", "Khỉ đuôi ngắn"], "tuoi_tho": "thuc_an"]

               tuoi_tho         loai   thuc_an
dong_vat
Sao la               25        có vú  thực vật
Khỉ đuôi ngắn        25  linh trưởng  thực vật

In [ ]:
# Lọc dữ liệu với điều kiện
animals.loc[animals["loai"] == "có vú", "tuoi_tho": "moi_truong_song"]

            tuoi_tho   loai   thuc_an moi_truong_song
dong_vat
Sao la            25  có vú  thực vật            Rừng
Voi châu Á        70  có vú  thực vật            Rừng

In [33]:
# Đọc và ghi file csv
import pandas as pd
data = {
    "name": ["John", "Jane", "Doe"],
    "age": [30, 25, 35],
    "city": ["New York", "LA", "Chicago"]
}

df = pd.DataFrame(data)
df.to_csv('output.csv', index=False)

In [39]:
df = pd.read_csv("output.csv")
df

   name  age      city
0  John   30  New York
1  Jane   25        LA
2   Doe   35   Chicago
3    An   16    Hà Nội
4  Minh   17    Hà Nội
5  Tuấn   17    Hà Nội

In [44]:
# Đọc và ghi file excel
import pandas as pd
data = {
    "name": ["John", "Jane", "Doe"],
    "age": [30, 25, 35],
    "city": ["New York", "LA", "Chicago"]
}
df = pd.DataFrame(data)
# df.to_excel("output.xlsx", index=False, engine="openpyxl", sheet_name="Information")

df1 = pd.read_excel("output.xlsx")
df1

   name  age      city
0  John   30  New York
1  Jane   25        LA
2   Doe   35   Chicago
3    An   16    Hà Nội
4  Minh   17    Hà Nội
5  Tuấn   17    Hà Nội