In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Tên": ["Kiên", "Lan", "Minh"],
    "Tuổi": [23, 25, 30],
    "Thành phố": ["Hà Nội", "Đà Nẵng", "HCM"]
})

df

    Tên  Tuổi Thành phố
0  Kiên    23    Hà Nội
1   Lan    25   Đà Nẵng
2  Minh    30       HCM

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Tên": ["Kiên", "Lan", "Minh"],
    "Tuổi": [23, 25, 30],
    "Thành phố": ["Hà Nội", "Đà Nẵng", "HCM"]
})

df

    Tên  Tuổi Thành phố
0  Kiên    23    Hà Nội
1   Lan    25   Đà Nẵng
2  Minh    30       HCM

In [5]:
print("HELLO WORLD")

HELLO WORLD

In [ ]:
# Import thư viện pandas
import pandas as pd

In [7]:
# Khởi tạo Series từ list
fruits = pd.Series(["apple", "banana", "orange", "cherry"])
fruits

0     apple
1    banana
2    orange
3    cherry
dtype: object

In [8]:
# Thay đổi chỉ số
fruits = pd.Series(["apple", "banana", "orange", "cherry"], index=["A", "B", "C", "D"])
fruits

A     apple
B    banana
C    orange
D    cherry
dtype: object

In [14]:
# Khởi tạo Series từ dictionary
fruit_dict = {
    'A': 'apple',
    'B': 'banana',
    'C': 'cherry',
    'D': 'orange'
}

fruits = pd.Series(fruit_dict)
fruits

A     apple
B    banana
C    cherry
D    orange
dtype: object

In [20]:
fruits['A']

'apple'

In [21]:
# Lấy 2 phần tử đầu
fruits[:2]

A     apple
B    banana
dtype: object

In [32]:
temperature_dict = {
    "Hà Nội": 28,
    "Đà Nẵng": 30,
    "TP.Hồ Chí Minh": 35,
    "Huế": 29,
    "Hải Phòng": 26,
    "Nghệ An": 30,
    "Lâm Đồng": 34
}
temperature = pd.Series(temperature_dict)
temperature

Hà Nội            28
Đà Nẵng           30
TP.Hồ Chí Minh    35
Huế               29
Hải Phòng         26
Nghệ An           30
Lâm Đồng          34
dtype: int64

In [34]:
# Một số hàm thống kê nhanh
print(temperature.max()) # Lấy giá trị lớn nhất
print(temperature.min()) #Lấy giá trị bé nhất
print(temperature.sum()) #Lấy tổng
print(temperature.mean()) # Lấy trung bình cộng
print(temperature.median()) #Lấy trung vị
print(temperature.mode()) #Lấy giá trị xuất hiện nhiều nhất

35
26
212
30.285714285714285
30.0
0    30
dtype: int64

In [3]:
import pandas as pd
weights = pd.Series({
    "Hoa": 37,
    "Nam": 48,
    "Hải": 42,
    "Linh": 39,
    "Nhân": 41,
    "Phương": 38,
    "Thu": 40,
    "Vũ": 40,
    "Bảo": 100
})

print(weights.mean())
print(weights.median())
print(weights.mode())

47.22222222222222
40.0
0    40
dtype: int64

In [4]:
import pandas as pd
ratings = pd.Series([4, 3, 1, 1, 5, 1, 1])
print(ratings.mean())
print(ratings.median())
print(ratings.mode())

2.2857142857142856
1.0
0    1
dtype: int64