In [21]:
import pandas as pd
df = pd.read_csv("2024 Billionaire List.csv", index_col=0)
df["2024 Net Worth"] = df["2024 Net Worth"].apply(lambda x : x[1 : -1])
df["2024 Net Worth"] = pd.to_numeric(df["2024 Net Worth"])
df.dtypes
# df.head()

Age                   float64
2024 Net Worth        float64
Industry               object
Source of Wealth       object
Title                  object
Organization           object
Self-Made                bool
Self-Made Score       float64
Philanthropy Score    float64
Residence              object
Citizenship            object
Gender                 object
Marital Status         object
Children              float64
Education              object
dtype: object

In [27]:
df["Age"] = df["Age"].astype('Int64')
df.dtypes

Age                     Int64
2024 Net Worth        float64
Industry               object
Source of Wealth       object
Title                  object
Organization           object
Self-Made                bool
Self-Made Score       float64
Philanthropy Score    float64
Residence              object
Citizenship            object
Gender                 object
Marital Status         object
Children              float64
Education              object
dtype: object

In [ ]:
# Lấy ra 2 cột Industry và 2024 Net Worth và nhóm theo cột Industry
df[["Industry", "2024 Net Worth"]].groupby("Industry")

In [ ]:
# Tính tổng giá trị từng Industry
df[["Industry", "2024 Net Worth"]].groupby("Industry").sum()

                            2024 Net Worth
Industry
Automotive                           548.3
Construction & Engineering           145.0
Diversified                         1137.0
Energy                               504.5
Fashion & Retail                    1958.2
Finance & Investments               2175.3
Food & Beverage                      997.6
Gambling & Casinos                   115.7
Healthcare                           681.8
Logistics                            268.5
Manufacturing                       1015.7
Media & Entertainment                367.1
Metals & Mining                      475.5
Real Estate                          667.1
Service                              176.2
Sports                               169.2
Technology                          2601.7
Telecom                              205.2

In [30]:
df_industry = df[["Industry", "2024 Net Worth"]].groupby("Industry").sum()
df_industry = df_industry.sort_values(by="2024 Net Worth", ascending=False)
df_industry

                            2024 Net Worth
Industry
Technology                          2601.7
Finance & Investments               2175.3
Fashion & Retail                    1958.2
Diversified                         1137.0
Manufacturing                       1015.7
Food & Beverage                      997.6
Healthcare                           681.8
Real Estate                          667.1
Automotive                           548.3
Energy                               504.5
Metals & Mining                      475.5
Media & Entertainment                367.1
Logistics                            268.5
Telecom                              205.2
Service                              176.2
Sports                               169.2
Construction & Engineering           145.0
Gambling & Casinos                   115.7

In [32]:
import pycountry_convert as pc
def get_continent(country_name):
    try:
        country_code = pc.country_name_to_country_alpha2(country_name, cn_name_format="default")
        continent_code = pc.country_alpha2_to_continent_code(country_code)
        continent_name = pc.convert_continent_code_to_continent_name(continent_code)
        return continent_name
    except:
        return "Unknown"
    
df["Continent"] = df["Citizenship"].apply(get_continent)
df[["Continent", "2024 Net Worth"]].groupby("Continent").mean()

               2024 Net Worth
Continent
Africa               4.185000
Asia                 3.748651
Europe               5.088183
North America        6.869426
Oceania              4.430769
South America        3.779310
Unknown              7.200000