In [21]:
import pandas as pd
df = pd.read_csv("2024 Billionaire List.csv", index_col=0)
df["2024 Net Worth"] = df["2024 Net Worth"].apply(lambda x : x[1 : -1])
df["2024 Net Worth"] = pd.to_numeric(df["2024 Net Worth"])
df.dtypes
# df.head()

Age                   float64
2024 Net Worth        float64
Industry               object
Source of Wealth       object
Title                  object
Organization           object
Self-Made                bool
Self-Made Score       float64
Philanthropy Score    float64
Residence              object
Citizenship            object
Gender                 object
Marital Status         object
Children              float64
Education              object
dtype: object

In [ ]:
# Chuyển cột Age thành kiểu dữ liệu int
df["Age"] = df["Age"].astype('Int64')
df.dtypes

Age                     Int64
2024 Net Worth        float64
Industry               object
Source of Wealth       object
Title                  object
Organization           object
Self-Made                bool
Self-Made Score       float64
Philanthropy Score    float64
Residence              object
Citizenship            object
Gender                 object
Marital Status         object
Children              float64
Education              object
dtype: object

In [ ]:
# Lấy ra 2 cột Industry và 2024 Net Worth và nhóm theo cột Industry
df[["Industry", "2024 Net Worth"]].groupby("Industry")

In [ ]:
# Tính tổng giá trị từng Industry
df[["Industry", "2024 Net Worth"]].groupby("Industry").sum()

                            2024 Net Worth
Industry
Automotive                           548.3
Construction & Engineering           145.0
Diversified                         1137.0
Energy                               504.5
Fashion & Retail                    1958.2
Finance & Investments               2175.3
Food & Beverage                      997.6
Gambling & Casinos                   115.7
Healthcare                           681.8
Logistics                            268.5
Manufacturing                       1015.7
Media & Entertainment                367.1
Metals & Mining                      475.5
Real Estate                          667.1
Service                              176.2
Sports                               169.2
Technology                          2601.7
Telecom                              205.2

In [ ]:
# Sắp xếp theo giá trị giảm dần
df_industry = df[["Industry", "2024 Net Worth"]].groupby("Industry").sum()
df_industry = df_industry.sort_values(by="2024 Net Worth", ascending=False)
df_industry

                            2024 Net Worth
Industry
Technology                          2601.7
Finance & Investments               2175.3
Fashion & Retail                    1958.2
Diversified                         1137.0
Manufacturing                       1015.7
Food & Beverage                      997.6
Healthcare                           681.8
Real Estate                          667.1
Automotive                           548.3
Energy                               504.5
Metals & Mining                      475.5
Media & Entertainment                367.1
Logistics                            268.5
Telecom                              205.2
Service                              176.2
Sports                               169.2
Construction & Engineering           145.0
Gambling & Casinos                   115.7

In [ ]:
import pycountry_convert as pc
def get_continent(country_name):
    try:
        country_code = pc.country_name_to_country_alpha2(country_name, cn_name_format="default")
        continent_code = pc.country_alpha2_to_continent_code(country_code)
        continent_name = pc.convert_continent_code_to_continent_name(continent_code)
        return continent_name
    except:
        return "Unknown"
    
df["Continent"] = df["Citizenship"].apply(get_continent)
df[["Continent", "2024 Net Worth"]].groupby("Continent").mean()

               2024 Net Worth
Continent
Africa               4.185000
Asia                 3.748651
Europe               5.088183
North America        6.869426
Oceania              4.430769
South America        3.779310
Unknown              7.200000

:

In [ ]:
import pandas as pd
df = pd.read_csv("hockey_players_data.csv")
# Kiểm tra số giá trị lỗi ở mỗi cột
df.isnull().sum()

number           0
name             0
position         0
games_played     0
goals           10
assists          0
PIM              0
birthdate        0
age              0
birthplace       2
weight          11
height           1
dtype: int64

In [16]:
df

,number,name,position,games_played,goals,assists,PIM,age,height
0,13,Mikyla Grant-Mentis,F,6,5.0,4,4,22,5.08
1,44,Lindsay Eastwood,D,6,4.0,5,10,23,5.08
2,2,Taylor Woods,F,6,4.0,4,4,26,5.04
3,19,Brooke Boquist,F,6,2.0,2,2,24,5.03
4,67,Emma Woods,F,6,0.0,4,0,24,5.04
5,21,Breanne Wilson-Bennett,F,6,2.0,4,2,24,5.03
6,27,Amy Curlew,F,6,0.0,2,4,23,5.07
7,27,Sarah-Eve Coutu-Godbout,F,6,2.0,4,2,23,NaN
8,18,Taytum Clairmont,F,6,1.0,3,21,26,5.11
9,18,Taytum Clairmont,F,6,1.0,3,21,26,5.11
10,27,Shiann Darkangelo,F,6,0.0,3,0,22,5.08
11,7,Mackenzie MacNeil,F,6,2.0,1,1,24,5.08
12,12,Emily Fluke,F,6,1.0,4,4,27,5.07
13,4,Sarah Steele,D,6,1.0,4,4,25,5.06
14,23,Megan Quinn,D,6,1.0,0,0,22,5.05
15,25,Emma Greco,D,6,0.0,0,0,22,5.08
16,15,Natalie Marcuzzi,F,6,0.0,0,0,27,5.08
17,91,Jenna McParland,F,6,0.0,0,0,33,5.08
18,91,Henna McParland,M,5,0.0,0,0,33,5.08
19,27,Kristen Barbara,D,6,0.0,0,0,26,5.10
20,29,Julie Allen,F,6,0.0,0,0,26,5.07
21,34,Elaine Chuli,G,6,0.0,0,0,24,5.11

In [ ]:
# Xóa hàng có giá trị lỗi
df.dropna()

,number,name,position,games_played,goals,assists,PIM,birthdate,age,birthplace,weight,height
2,2,Taylor Woods,F,6,4.0,4,4,4/12/94,26,"Thunder Bay,ONT",160.0,5.04
8,18,Taytum Clairmont,F,6,1.0,3,21,11/28/93,26,"Royal Oak, MI",177.0,5.11
9,18,Taytum Clairmont,F,6,1.0,3,21,11/28/93,26,"Royal Oak, MI",177.0,5.11
13,4,Sarah Steele,D,6,1.0,4,4,9/11/94,25,"Belleville, ONT",145.0,5.06
14,23,Megan Quinn,D,6,1.0,0,0,3/9/95,22,"Burlington, ONT",165.0,5.05

In [ ]:
# Xóa cột có giá trị lỗi
df.dropna(axis=1)

,number,name,position,games_played,assists,PIM,birthdate,age
0,13,Mikyla Grant-Mentis,F,6,4,4,7/15/98,22
1,44,Lindsay Eastwood,D,6,5,10,1/14/97,23
2,2,Taylor Woods,F,6,4,4,4/12/94,26
3,19,Brooke Boquist,F,6,2,2,7/27/96,24
4,67,Emma Woods,F,6,4,0,9/8/96,24
5,21,Breanne Wilson-Bennett,F,6,4,2,3/5/96,24
6,27,Amy Curlew,F,6,2,4,3/4/97,23
7,27,Sarah-Eve Coutu-Godbout,F,6,4,2,6/16/97,23
8,18,Taytum Clairmont,F,6,3,21,11/28/93,26
9,18,Taytum Clairmont,F,6,3,21,11/28/93,26
10,27,Shiann Darkangelo,F,6,3,0,1/4/97,22
11,7,Mackenzie MacNeil,F,6,1,1,9/3/96,24
12,12,Emily Fluke,F,6,4,4,5/8/94,27
13,4,Sarah Steele,D,6,4,4,9/11/94,25
14,23,Megan Quinn,D,6,0,0,3/9/95,22
15,25,Emma Greco,D,6,0,0,4/27/97,22
16,15,Natalie Marcuzzi,F,6,0,0,10/30/97,27
17,91,Jenna McParland,F,6,0,0,5/2/87,33
18,91,Henna McParland,M,5,0,0,3/2/87,33
19,27,Kristen Barbara,D,6,0,0,5/16/94,26
20,29,Julie Allen,F,6,0,0,5/16/94,26
21,34,Elaine Chuli,G,6,0,0,7/16/96,24

In [ ]:
# Xóa những cột không cần thiết theo yêu cầu
df.drop(["birthdate", "birthplace", "weight"], axis=1, inplace=True)
df

,number,name,position,games_played,goals,assists,PIM,age,height
0,13,Mikyla Grant-Mentis,F,6,5.0,4,4,22,5.08
1,44,Lindsay Eastwood,D,6,4.0,5,10,23,5.08
2,2,Taylor Woods,F,6,4.0,4,4,26,5.04
3,19,Brooke Boquist,F,6,2.0,2,2,24,5.03
4,67,Emma Woods,F,6,NaN,4,0,24,5.04
5,21,Breanne Wilson-Bennett,F,6,2.0,4,2,24,5.03
6,27,Amy Curlew,F,6,NaN,2,4,23,5.07
7,27,Sarah-Eve Coutu-Godbout,F,6,2.0,4,2,23,NaN
8,18,Taytum Clairmont,F,6,1.0,3,21,26,5.11
9,18,Taytum Clairmont,F,6,1.0,3,21,26,5.11
10,27,Shiann Darkangelo,F,6,NaN,3,0,22,5.08
11,7,Mackenzie MacNeil,F,6,2.0,1,1,24,5.08
12,12,Emily Fluke,F,6,1.0,4,4,27,5.07
13,4,Sarah Steele,D,6,1.0,4,4,25,5.06
14,23,Megan Quinn,D,6,1.0,0,0,22,5.05
15,25,Emma Greco,D,6,NaN,0,0,22,5.08
16,15,Natalie Marcuzzi,F,6,NaN,0,0,27,5.08
17,91,Jenna McParland,F,6,NaN,0,0,33,5.08
18,91,Henna McParland,M,5,NaN,0,0,33,5.08
19,27,Kristen Barbara,D,6,NaN,0,0,26,5.10
20,29,Julie Allen,F,6,NaN,0,0,26,5.07
21,34,Elaine Chuli,G,6,NaN,0,0,24,5.11

In [ ]:
# Lấy ra những giá trị goals bị lỗi
df[df.goals.isna()]

,number,name,position,games_played,goals,assists,PIM,age,height
4,67,Emma Woods,F,6,NaN,4,0,24,5.04
6,27,Amy Curlew,F,6,NaN,2,4,23,5.07
10,27,Shiann Darkangelo,F,6,NaN,3,0,22,5.08
15,25,Emma Greco,D,6,NaN,0,0,22,5.08
16,15,Natalie Marcuzzi,F,6,NaN,0,0,27,5.08
17,91,Jenna McParland,F,6,NaN,0,0,33,5.08
18,91,Henna McParland,M,5,NaN,0,0,33,5.08
19,27,Kristen Barbara,D,6,NaN,0,0,26,5.10
20,29,Julie Allen,F,6,NaN,0,0,26,5.07
21,34,Elaine Chuli,G,6,NaN,0,0,24,5.11

In [ ]:
# Thay thế những giá trị goals bị lỗi thành giá trị 0
df.goals = df.goals.fillna(0)
df.tail()

,number,name,position,games_played,goals,assists,PIM,age,height
17,91,Jenna McParland,F,6,0.0,0,0,33,5.08
18,91,Henna McParland,M,5,0.0,0,0,33,5.08
19,27,Kristen Barbara,D,6,0.0,0,0,26,5.10
20,29,Julie Allen,F,6,0.0,0,0,26,5.07
21,34,Elaine Chuli,G,6,0.0,0,0,24,5.11

In [ ]:
# Kiểm tra số hàng bị trùng
df.duplicated().sum()

np.int64(1)

In [ ]:
# Xóa hàng bị trùng
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)