In [4]:
import pandas as pd
df = pd.read_csv("car-sales-data.csv")
# df.drop(["Colour", "Doors"])
df["Odometer"] = df["Odometer"].fillna(df['Odometer'].mean())
df["Odometer"] = df["Odometer"].round(0).astype(int)

df['Price'] = df['Price'].fillna('$0')
df

     Make Colour  Odometer  Doors    Price
0  Toyota  White    150043    4.0   $4,000
1   Honda    Red     87899    4.0   $5,000
2  Toyota   Blue     92303    3.0   $7,000
3     BMW  Black     11179    5.0  $22,000
4  Nissan  White    213095    4.0   $3,500
5  Toyota  Green     92303    4.0   $4,500
6   Honda    NaN     92303    4.0   $7,500
7   Honda   Blue     92303    4.0       $0
8  Toyota  White     60000    NaN       $0
9     NaN  White     31600    4.0   $9,700

In [1]:
df.drop(["Colour", "Doors"], replace=True)
df["Odometer"] = df["Odometer"].fillna(df['Odometer'].mean())
df["Odometer"] = df["Odometer"].round(0).astype(int)

df['Price'] = df['Price'].fillna('$0')
df

NameError: name 'df' is not defined

In [5]:
df['Price'] = df['Price'].apply(lambda x: float(x.replace('$','').replace(',','')))
df

     Make Colour  Odometer  Doors    Price
0  Toyota  White    150043    4.0   4000.0
1   Honda    Red     87899    4.0   5000.0
2  Toyota   Blue     92303    3.0   7000.0
3     BMW  Black     11179    5.0  22000.0
4  Nissan  White    213095    4.0   3500.0
5  Toyota  Green     92303    4.0   4500.0
6   Honda    NaN     92303    4.0   7500.0
7   Honda   Blue     92303    4.0      0.0
8  Toyota  White     60000    NaN      0.0
9     NaN  White     31600    4.0   9700.0

In [6]:
max_price = df['Price'].max()
max_price_car = df[df['Price'] == max_price]
max_price_car

  Make Colour  Odometer  Doors    Price
3  BMW  Black     11179    5.0  22000.0

In [8]:
df_valid = df[df['Price'] > 0]
df_valid['Price_per_km'] = df_valid['Price'] / df_valid['Odometer']

min_ratio = df_valid['Price_per_km'].min()
cheapest_per_km = df_valid[df_valid['Price_per_km'] == min_ratio]
cheapest_per_km

C:\Users\Admin\AppData\Local\Temp\ipykernel_22240\257988524.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid['Price_per_km'] = df_valid['Price'] / df_valid['Odometer']

     Make Colour  Odometer  Doors   Price  Price_per_km
4  Nissan  White    213095    4.0  3500.0      0.016425

In [16]:
average_price_by_make = df[["Make", "Price"]].groupby("Make").mean().round(0)
average_price_by_make

          Price
Make
BMW     22000.0
Honda    4167.0
Nissan   3500.0
Toyota   3875.0

In [17]:
max_average_price = average_price_by_make.max()
highest_avg_make = average_price_by_make[average_price_by_make == max_average_price]
highest_avg_make

          Price
Make
BMW     22000.0
Honda       NaN
Nissan      NaN
Toyota      NaN